# Generated by Django 2.2.2 on 2019-06-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
