# Generated by Django 2.2.2 on 2019-06-23 23:55

import board.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('hit', models.IntegerField(default=0)),
                ('regdate', models.DateTimeField(auto_now=True)),
                ('groupno', models.IntegerField(default=0)),
                ('orderno', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=board.models.BoardStatus)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
