# Generated by Django 2.2.2 on 2019-06-24 06:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default=None, max_length=15, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2019, 6, 24, 6, 37, 25, 76034, tzinfo=utc), null=True)),
                ('post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
            ],
        ),
    ]
